DROP TABLE IF EXISTS CONNECTOR_SQL CASCADE;
DROP TABLE IF EXISTS CONNECTOR_REST CASCADE;
DROP TABLE IF EXISTS ENGINE CASCADE;
DROP TABLE IF EXISTS CONNECTOR CASCADE;

CREATE TABLE ENGINE (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO ENGINE VALUES
    ('3e3f9730-ce5a-442d-85fb-183b853bfafa', 'ORACLE'),
    ('4df76931-b174-4935-94a3-b87936d1d02a', 'POSTGRESQL');

CREATE TABLE CONNECTOR (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE CONNECTOR_REST (
    id UUID PRIMARY KEY,
    connector_id INT REFERENCES Connector(id) ON DELETE CASCADE,
    url VARCHAR(255) NOT NULL,
    method VARCHAR(10) NOT NULL,
    headers TEXT
);

CREATE TABLE CONNECTOR_SQL (
    id UUID PRIMARY KEY,
    connector_id INT REFERENCES Connector(id) ON DELETE CASCADE,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    database VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    engine_id UUID,
    test_query TEXT,
    FOREIGN KEY (engine_id) REFERENCES ENGINE(id)
);
